# Generated by Django 4.2.1 on 2023-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_db_created_at_alter_rd_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='emp_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rd',
            name='emp_id',
            field=models.IntegerField(default=0),
        ),
    ]
