# Generated by Django 4.2.1 on 2023-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_db_emp_id_rd_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='emp_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rd',
            name='emp_id',
            field=models.CharField(max_length=20),
        ),
    ]
